[package]
name = "stratum_ping"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version="3.1.6",features=["derive"] }
native-tls = "0.2.8"
miniserde ="0.1.24"


[profile.release]
codegen-units = 1
debug = false
incremental = true
lto = true
